services:
  # Next.js Application
  app:
    build: .
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://hotel_user:hotel_password@db:5432/hotel_db
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - hotel-network

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./prisma/migrations:/docker-entrypoint-initdb.d
    networks:
      - hotel-network

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hotel-network
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:

networks:
  hotel-network:
    driver: bridge
